spring:
  application:
    name: "takehome"
  jackson:
    deserialization:
      unwrap-root-value: true
  jmx:
    enabled: false
  autoconfigure:
    exclude:
    - org.springframework.boot.autoconfigure.web.servlet.error.ErrorMvcAutoConfiguration
external-api:
  url: "https://countries.trevorblades.com/graphql"
rate-limit:
  authenticated: 20
  anonymous: 5
  duration: 1
logging:
  level:
    root: WARN
  file:
    name: app.log
    
    
    
